[package]
name = "TokenBridge"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "9ea7599fe5ca95454e43038ef41884753cee753c"

[dependencies.Wormhole]
local = "../wormhole"

[addresses]
token_bridge = "_"
